export type PublicCourse = "ライト" | "スタンダード" | "プレミアム";
export interface PublicMetric { course: PublicCourse; stakeYen:number; returnYen:number; roiPct:number|null; settledTickets:number; }
export interface PublicMonthlyMetric extends PublicMetric { month:string; }
export interface PublicRace { raceId:string; raceDate:string; venue:string; raceNo:number; raceName:string; startTimeJst:string|null; surface:string|null; distanceM:number|null; direction:string|null; weather:string|null; trackCondition:string|null; status:string; snapshotStatus:string|null; selected:number; frozen:number; ticketCount:number; }
export interface PublicTicket { betType:string; combination:string; officialOdds:number|null; conditionText:string; lightStake:number; standardStake:number; premiumStake:number; payoutPer100:number|null; }
export interface PublicRunner { horseNo:number; frameNo:number|null; horseName:string; sexAge:string|null; horseWeight:number|null; weightChange:number|null; jockey:string|null; assignedWeight:number|null; trainer:string|null; winOdds:number|null; popularity:number|null; runnerStatus:string; finishPosition:number|null; final3f:number|null; }

export async function ensurePublicSchema(db:D1Database):Promise<void>{
  const sqls=[
`CREATE TABLE IF NOT EXISTS rt_public_race_snapshots(race_id TEXT PRIMARY KEY,race_date TEXT NOT NULL,venue TEXT NOT NULL,race_no INTEGER NOT NULL,selected INTEGER NOT NULL CHECK(selected IN (0,1)),status TEXT NOT NULL,published_at TEXT,publish_deadline_utc TEXT,source_cutoff TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
`CREATE INDEX IF NOT EXISTS rt_pub_race_date ON rt_public_race_snapshots(race_date,venue,race_no)`,
`CREATE TABLE IF NOT EXISTS rt_public_ticket_snapshots(race_id TEXT NOT NULL,bet_type TEXT NOT NULL,combination TEXT NOT NULL,official_odds REAL,condition_text TEXT NOT NULL,rule_strength REAL,matched_rule_count INTEGER NOT NULL DEFAULT 1,light_stake INTEGER NOT NULL,standard_stake INTEGER NOT NULL,premium_stake INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(race_id,bet_type,combination))`,
`CREATE INDEX IF NOT EXISTS rt_pub_ticket_race ON rt_public_ticket_snapshots(race_id)`,
`CREATE TABLE IF NOT EXISTS rt_public_ticket_settlements(race_id TEXT NOT NULL,bet_type TEXT NOT NULL,combination TEXT NOT NULL,payout_per_100 INTEGER NOT NULL,settled_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(race_id,bet_type,combination))`,
`CREATE TABLE IF NOT EXISTS rt_public_venue_day_freezes(race_date TEXT NOT NULL,venue TEXT NOT NULL,selected_race_ids_json TEXT NOT NULL,frozen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(race_date,venue))`,
`CREATE TABLE IF NOT EXISTS rt_public_rule_catalog(rule_no INTEGER PRIMARY KEY,bet_type TEXT NOT NULL,condition_text TEXT NOT NULL)`,
`CREATE TRIGGER IF NOT EXISTS rt_pub_ticket_no_update BEFORE UPDATE ON rt_public_ticket_snapshots BEGIN SELECT RAISE(ABORT,'IMMUTABLE_PUBLIC_TICKET'); END`,
`CREATE TRIGGER IF NOT EXISTS rt_pub_ticket_no_delete BEFORE DELETE ON rt_public_ticket_snapshots BEGIN SELECT RAISE(ABORT,'IMMUTABLE_PUBLIC_TICKET'); END`,
`CREATE TRIGGER IF NOT EXISTS rt_pub_race_no_update BEFORE UPDATE ON rt_public_race_snapshots BEGIN SELECT RAISE(ABORT,'IMMUTABLE_PUBLIC_RACE'); END`,
`CREATE TRIGGER IF NOT EXISTS rt_pub_race_no_delete BEFORE DELETE ON rt_public_race_snapshots BEGIN SELECT RAISE(ABORT,'IMMUTABLE_PUBLIC_RACE'); END`,
`CREATE TRIGGER IF NOT EXISTS rt_pub_freeze_no_update BEFORE UPDATE ON rt_public_venue_day_freezes BEGIN SELECT RAISE(ABORT,'IMMUTABLE_PUBLIC_FREEZE'); END`,
`CREATE TRIGGER IF NOT EXISTS rt_pub_freeze_no_delete BEFORE DELETE ON rt_public_venue_day_freezes BEGIN SELECT RAISE(ABORT,'IMMUTABLE_PUBLIC_FREEZE'); END`,
`CREATE TRIGGER IF NOT EXISTS rt_pub_settle_no_update BEFORE UPDATE ON rt_public_ticket_settlements BEGIN SELECT RAISE(ABORT,'IMMUTABLE_PUBLIC_SETTLEMENT'); END`,
`CREATE TRIGGER IF NOT EXISTS rt_pub_settle_no_delete BEFORE DELETE ON rt_public_ticket_settlements BEGIN SELECT RAISE(ABORT,'IMMUTABLE_PUBLIC_SETTLEMENT'); END`
  ];
  for(const sql of sqls) await db.prepare(sql).run();
}
function n(v:unknown):number{return Number(v??0)}
export async function getPublicMetrics(db:D1Database):Promise<PublicMetric[]>{
 const row=await db.prepare(`SELECT SUM(t.light_stake) ls,SUM(t.standard_stake) ss,SUM(t.premium_stake) ps,SUM(CASE WHEN s.payout_per_100 IS NULL THEN 0 ELSE t.light_stake*s.payout_per_100/100 END) lr,SUM(CASE WHEN s.payout_per_100 IS NULL THEN 0 ELSE t.standard_stake*s.payout_per_100/100 END) sr,SUM(CASE WHEN s.payout_per_100 IS NULL THEN 0 ELSE t.premium_stake*s.payout_per_100/100 END) pr,SUM(CASE WHEN s.payout_per_100 IS NULL THEN 0 ELSE 1 END) settled FROM rt_public_ticket_snapshots t LEFT JOIN rt_public_ticket_settlements s ON s.race_id=t.race_id AND s.bet_type=t.bet_type AND s.combination=t.combination`).first<Record<string,unknown>>();
 const x=row??{}; const mk=(course:PublicCourse,stake:number,ret:number):PublicMetric=>({course,stakeYen:stake,returnYen:ret,roiPct:stake>0?ret/stake*100:null,settledTickets:n(x.settled)});
 return [mk('ライト',n(x.ls),n(x.lr)),mk('スタンダード',n(x.ss),n(x.sr)),mk('プレミアム',n(x.ps),n(x.pr))];
}
export async function getPublicMonthlyMetrics(db:D1Database):Promise<PublicMonthlyMetric[]>{
 const rows=await db.prepare(`SELECT substr(r.race_date,1,7) month,SUM(t.light_stake) ls,SUM(t.standard_stake) ss,SUM(t.premium_stake) ps,SUM(CASE WHEN s.payout_per_100 IS NULL THEN 0 ELSE t.light_stake*s.payout_per_100/100 END) lr,SUM(CASE WHEN s.payout_per_100 IS NULL THEN 0 ELSE t.standard_stake*s.payout_per_100/100 END) sr,SUM(CASE WHEN s.payout_per_100 IS NULL THEN 0 ELSE t.premium_stake*s.payout_per_100/100 END) pr,SUM(CASE WHEN s.payout_per_100 IS NULL THEN 0 ELSE 1 END) settled FROM rt_public_ticket_snapshots t JOIN rt_races r ON r.race_id=t.race_id LEFT JOIN rt_public_ticket_settlements s ON s.race_id=t.race_id AND s.bet_type=t.bet_type AND s.combination=t.combination GROUP BY substr(r.race_date,1,7) ORDER BY month DESC`).all<Record<string,unknown>>();
 const out:PublicMonthlyMetric[]=[]; for(const x of rows.results){for(const [c,sk,rk] of [['ライト','ls','lr'],['スタンダード','ss','sr'],['プレミアム','ps','pr']] as const){const stake=n(x[sk]),ret=n(x[rk]);out.push({month:String(x.month),course:c,stakeYen:stake,returnYen:ret,roiPct:stake?ret/stake*100:null,settledTickets:n(x.settled)})}} return out;
}
export async function getRaceDates(db:D1Database):Promise<Array<{raceDate:string;venues:string[]}>>{const rows=await db.prepare(`SELECT race_date raceDate,GROUP_CONCAT(DISTINCT venue) venues FROM rt_races WHERE race_date>='2024-05-04' GROUP BY race_date ORDER BY race_date DESC`).all<{raceDate:string;venues:string}>();return rows.results.map(r=>({raceDate:r.raceDate,venues:(r.venues||'').split(',').filter(Boolean)}));}
export async function getRaces(db:D1Database,date:string,venue:string):Promise<PublicRace[]>{const rows=await db.prepare(`SELECT r.race_id raceId,r.race_date raceDate,r.venue,r.race_no raceNo,r.race_name raceName,r.start_time_jst startTimeJst,r.surface,r.distance_m distanceM,r.direction,r.weather,r.track_condition trackCondition,r.status,s.status snapshotStatus,CASE WHEN s.race_id IS NULL THEN 0 ELSE 1 END selected,CASE WHEN f.race_date IS NULL THEN 0 ELSE 1 END frozen,(SELECT COUNT(*) FROM rt_public_ticket_snapshots t WHERE t.race_id=r.race_id) ticketCount FROM rt_races r LEFT JOIN rt_public_race_snapshots s ON s.race_id=r.race_id LEFT JOIN rt_public_venue_day_freezes f ON f.race_date=r.race_date AND f.venue=r.venue WHERE r.race_date=? AND r.venue=? ORDER BY r.race_no`).bind(date,venue).all<PublicRace>();return rows.results.map(r=>({...r,raceNo:n(r.raceNo),distanceM:r.distanceM===null?null:n(r.distanceM),selected:n(r.selected),frozen:n(r.frozen),ticketCount:n(r.ticketCount)}));}
export async function getRaceDetail(db:D1Database,raceId:string):Promise<{race:PublicRace|null;tickets:PublicTicket[];runners:PublicRunner[]}>{
 const rr=await db.prepare(`SELECT r.race_id raceId,r.race_date raceDate,r.venue,r.race_no raceNo,r.race_name raceName,r.start_time_jst startTimeJst,r.surface,r.distance_m distanceM,r.direction,r.weather,r.track_condition trackCondition,r.status,s.status snapshotStatus,CASE WHEN s.race_id IS NULL THEN 0 ELSE 1 END selected,CASE WHEN f.race_date IS NULL THEN 0 ELSE 1 END frozen,(SELECT COUNT(*) FROM rt_public_ticket_snapshots t WHERE t.race_id=r.race_id) ticketCount FROM rt_races r LEFT JOIN rt_public_race_snapshots s ON s.race_id=r.race_id LEFT JOIN rt_public_venue_day_freezes f ON f.race_date=r.race_date AND f.venue=r.venue WHERE r.race_id=?`).bind(raceId).first<PublicRace>();
 const race=rr?{...rr,raceNo:n(rr.raceNo),distanceM:rr.distanceM===null?null:n(rr.distanceM),selected:n(rr.selected),frozen:n(rr.frozen),ticketCount:n(rr.ticketCount)}:null;
 const tickets=(await db.prepare(`SELECT t.bet_type betType,t.combination,t.official_odds officialOdds,t.condition_text conditionText,t.light_stake lightStake,t.standard_stake standardStake,t.premium_stake premiumStake,s.payout_per_100 payoutPer100 FROM rt_public_ticket_snapshots t LEFT JOIN rt_public_ticket_settlements s ON s.race_id=t.race_id AND s.bet_type=t.bet_type AND s.combination=t.combination WHERE t.race_id=? ORDER BY t.bet_type,t.combination`).bind(raceId).all<PublicTicket>()).results.map(x=>({...x,lightStake:n(x.lightStake),standardStake:n(x.standardStake),premiumStake:n(x.premiumStake),officialOdds:x.officialOdds===null?null:Number(x.officialOdds),payoutPer100:x.payoutPer100===null?null:n(x.payoutPer100)}));
 const runners=(await db.prepare(`SELECT rr.horse_no horseNo,rr.frame_no frameNo,rr.horse_name horseName,rr.sex_age sexAge,rr.horse_weight horseWeight,rr.weight_change weightChange,rr.jockey,rr.assigned_weight assignedWeight,rr.trainer,rr.win_odds winOdds,rr.popularity,rr.runner_status runnerStatus,rs.finish_position finishPosition,rs.final3f FROM rt_runners rr LEFT JOIN rt_results rs ON rs.race_id=rr.race_id AND rs.horse_no=rr.horse_no WHERE rr.race_id=? ORDER BY rr.horse_no`).bind(raceId).all<PublicRunner>()).results;
 return {race,tickets,runners};
}
export async function getRuleCatalog(db:D1Database){const rows=await db.prepare(`SELECT rule_no ruleNo,bet_type betType,condition_text conditionText FROM rt_public_rule_catalog ORDER BY bet_type,rule_no`).all<{ruleNo:number;betType:string;conditionText:string}>();return rows.results;}
