import publicSite from "./public-site-entry-v3.js";
import { isFrozenSelectedRace } from "./v1/frozen-public-data.js";
import { isFrozenHitRace } from "./v1/frozen-hit-races.js";
import type { Env } from "./v1/types.js";

const BAD = new Set(["検索ウィンドウ","出馬表","レース結果","関連メニュー","コースレコード","払戻金"]);
type DayRace={raceId:string;raceDate:string;venue:string;raceNo:number;raceName:string;status:string;publicState?:{code:string;label:string;deadline:string|null}};
type BetSummary={raceId:string;betCount:number;settledCount:number;returnYen:number};
function today(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const g=(t:string)=>p.find(x=>x.type===t)?.value??"";return `${g("year")}-${g("month")}-${g("day")}`;}
function bad(s:string|undefined){return !s||BAD.has(s.trim())||s.includes("検索ウィンドウ");}
function derive(c:string|null,n:number){const x=(c??"").replace(/\s+/g," ").trim();const i=x.search(/(?:障害)?(?:2歳|3歳|4歳|3歳以上|4歳以上)(?:\s|　)*(?:未勝利|新馬|1勝クラス|2勝クラス|3勝クラス|オープン)/);if(i>0){const v=x.slice(0,i).trim();if(v&&!bad(v))return v;}return `${n}R`;}
async function names(db:D1Database,date:string){const r=await db.prepare(`SELECT race_id AS raceId,race_no AS raceNo,race_name AS raceName,conditions FROM rt_races WHERE race_date=?`).bind(date).all<{raceId:string;raceNo:number;raceName:string;conditions:string|null}>();return new Map(r.results.map(x=>[x.raceId,bad(x.raceName)?derive(x.conditions,Number(x.raceNo)):x.raceName]));}
async function summaries(db:D1Database,date:string){try{const r=await db.prepare(`SELECT b.race_id AS raceId,COUNT(*) AS betCount,SUM(CASE WHEN b.settlement_status='settled' THEN 1 ELSE 0 END) AS settledCount,COALESCE(SUM(CASE WHEN b.settlement_status='settled' THEN b.return_yen ELSE 0 END),0) AS returnYen FROM rt_public_bets b JOIN rt_races r ON r.race_id=b.race_id WHERE r.race_date=? GROUP BY b.race_id`).bind(date).all<BetSummary>();return new Map(r.results.map(x=>[x.raceId,{...x,betCount:Number(x.betCount),settledCount:Number(x.settledCount),returnYen:Number(x.returnYen)}]));}catch{return new Map<string,BetSummary>();}}
function state(r:DayRace,t:string,s?:BetSummary){const f=isFrozenSelectedRace(r.raceDate,r.venue,Number(r.raceNo));const sel=f||Boolean(s?.betCount);const fin=r.raceDate<t||r.status==="finished"||Boolean(s&&s.betCount>0&&s.settledCount>=s.betCount);if(sel&&fin){const hit=f?isFrozenHitRace(r.raceDate,r.venue,Number(r.raceNo)):Number(s?.returnYen??0)>0;return{code:hit?"hit":"miss",label:hit?"的中":"不的中",deadline:null};}if(sel)return{code:"buy",label:"買い目あり",deadline:null};if(fin)return{code:"skip",label:"見送り",deadline:null};return r.publicState??{code:"pending",label:"判定中",deadline:"発走15分前までに確定"};}
const CSS=`<style>.status.hit{background:#15543f;color:#c9f9e7}.status.miss{background:#512b32;color:#ffd0d5}.race-card:has(.status.hit){border-color:#36c993;box-shadow:inset 0 0 0 1px rgba(54,201,147,.22)}.race-card:has(.status.miss){border-color:#7b3e49}.bet-note{margin-top:10px;border:1px solid var(--line);border-radius:12px;background:var(--panel2);font-size:12px;color:var(--muted)}.bet-note summary{cursor:pointer;padding:10px 12px;font-weight:700;color:#cbd7e3}.bet-note ul{margin:0;padding:0 14px 10px 31px}.bet-note li{line-height:1.55;margin:3px 0}</style>`;
function compact(h:string){return h.replace(`<section class="panel" style="margin-top:12px"><h3>買い目について</h3><ul><li>このページに保存された買い目と購入額は、結果が出たあとも変更しません。</li><li>購入対象の判定は、その時点で利用できる情報だけを使って行います。</li><li>新しいレース結果は将来の改善材料に加えますが、このレースの記録には反映しません。</li></ul></section>`,`<details class="bet-note"><summary>買い目について</summary><ul><li>表示後の買い目・購入額は変更しません。</li><li>判定は予想時点で利用できた情報だけを使用します。</li><li>新しい結果は将来分の改善にのみ利用します。</li></ul></details>`);}
async function day(req:Request,env:Env,ctx:ExecutionContext){const u=new URL(req.url),d=u.searchParams.get("date")??"",nm=/^20\d{2}-\d{2}-\d{2}$/.test(d)?await names(env.DB,d):new Map<string,string>(),sm=/^20\d{2}-\d{2}-\d{2}$/.test(d)?await summaries(env.DB,d):new Map<string,BetSummary>();if(!publicSite.fetch)return new Response("NOT_FOUND",{status:404});const up=await publicSite.fetch(req,env,ctx);if(!up.ok)return up;const data=await up.json() as {races?:DayRace[];[k:string]:unknown};if(Array.isArray(data.races)){const t=today();data.races=data.races.map(r=>({...r,raceName:nm.get(r.raceId)??(bad(r.raceName)?`${r.raceNo}R`:r.raceName),publicState:state(r,t,sm.get(r.raceId))}));}return new Response(JSON.stringify(data),{status:up.status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store, max-age=0"}});}
async function html(req:Request,env:Env,ctx:ExecutionContext){if(!publicSite.fetch)return new Response("NOT_FOUND",{status:404});const up=await publicSite.fetch(req,env,ctx),ct=up.headers.get("content-type")??"";if(!ct.includes("text/html"))return up;let h=compact(await up.text()).replace("</head>",`${CSS}</head>`);const u=new URL(req.url);if(u.pathname.startsWith("/races/")){const id=decodeURIComponent(u.pathname.slice(7));const r=await env.DB.prepare(`SELECT race_date AS raceDate,venue,race_no AS raceNo,race_name AS raceName,conditions FROM rt_races WHERE race_id=?`).bind(id).first<{raceDate:string;venue:string;raceNo:number;raceName:string;conditions:string|null}>();if(r){const name=bad(r.raceName)?derive(r.conditions,Number(r.raceNo)):r.raceName;h=h.replaceAll("検索ウィンドウ",name);if(r.raceDate<today()&&isFrozenSelectedRace(r.raceDate,r.venue,Number(r.raceNo))){const hit=isFrozenHitRace(r.raceDate,r.venue,Number(r.raceNo));h=h.replaceAll(`<span class="status buy">買い目あり</span>`,`<span class="status ${hit?"hit":"miss"}">${hit?"的中":"不的中"}</span>`);}}}const hd=new Headers(up.headers);hd.delete("content-length");hd.set("cache-control","no-store, max-age=0");return new Response(h,{status:up.status,headers:hd});}
export default{async fetch(req:Request,env:Env,ctx:ExecutionContext){return new URL(req.url).pathname==="/api/public/day"?day(req,env,ctx):html(req,env,ctx);},async scheduled(c:ScheduledController,env:Env,ctx:ExecutionContext){if(publicSite.scheduled)await publicSite.scheduled(c,env,ctx);}} satisfies ExportedHandler<Env>;
